### ISSUE TITLE
Dummy service not necessary?

### ISSUE THREAD

**Issue by gongloo** [JeremyRuhland/klipper_network_status#1]
A quick read of the service code seems to indicate that it does nothing. What's the purpose for the dummy service?

**Comment by goopypanther** [comment]
Its a moonraker integration thing for the update manager, basically just restarts klipper so the new module is loaded and the service name sticks around to provide a log of it having happened.
The install.sh file also restarts the klipper service but its not clear from the moonraker docs if it gets run every time an update takes place or not. Mostly a moot point because I doubt there will ever be any future updates to this module that anyone will bother to pull in.

**Comment by goopypanther** [comment]
The dummy service is no longer required in moonraker afaik,  and it has been removed.
